---
title: "Day 2 Independent Activities"
author: "Heather"
format: html
editor: visual
execute: 
  warning: false
  echo: true
---

## Create some data, check the classes, index!

```{r}
vec_1 <- c(2, 5, 9, 10, 8, 12, 1, 0)
# Check the class of the vector
class(vec_1)

#What type of variable does it store?
typeof(vec_1)

vec_1_e3 <- vec_1[3]
vec_1_e3

vec_1_e1 <- vec_1[1]
vec_1_e1

vec_1_e5to7 <- vec_1[5:7]
vec_1_e5to7
```

```{r}
vec_1_char <- as.character(vec_1)
vec_1_char
# Notice the outputs of the vec_1_char all have quotes around the numbers
```

Vector 2

```{r}
vec_2 <- c(town = "Santa Barbara", location = "Rincon", swell = "south")
class(vec_2)
#the class for vec-2 is a character because it is the most flexible class that all teh elements can fit into

length(vec_2)
vec_2_e2 <- vec_2[2]
vec_2_e2
```

Create a Data Frame:

```{r}
df_1 <- data.frame(region = c("A","B","A","D"), species = c("otter", "great white", "sea lion", "gray whale"), count = c(12,2,36,6))
# View(df_1)

class(df_1)
class(df_1[,2])
max_count <- max(df_1[,3])
max_count
```
